# this properties applied when activeProfiles include "infra"
# NOTE: this style should be changed on spring-boot 2.4 - https://docs.spring.io/spring-boot/docs/2.4.0-M3/reference/html/spring-boot-features.html#boot-features-external-config-file-activation-properties

---
spring.profiles: dev

spring:
  r2dbc:
    url: TODO(dev mysql database)


---
spring.profiles: prod

spring:
  r2dbc:
    url: TODO(prod mysql database)

---
